language: python

# sudo: false

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7

addons:
  firefox: "62.0.3"
  chrome: stable


before_script:
  - "sudo apt-get install python-opencv"
  - "flake8 imgqa/*.py && flake8 imgqa/*/*.py"
  - "flake8 Examples/*.py && flake8 Examples/*/*.py"
  - "pycodestyle imgqa/*.py && pycodestyle Examples/*/*.py"
  - bash chrome_driver_install.sh

script:
  - pytest Examples/samplerestapitest.py
  - pytest Examples/FilesCompare/samplecomparisontest.py


deploy:
  provider: pypi
  user: Revant
  password: Revantpypi
  distributions: "sdist bdist_wheel"
  skip_existing: true
  skip_cleanup: true
  on:
      branch: master
